### ISSUE TITLE
undefined symbol: gzopen when import oalib

### ISSUE THREAD

**Issue by ohfang** [eendebakpt/oapackage#1]
CentOS 6
Linux 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
Python 2.6

>>> import oalib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site-packages/oalib.py", line 28, in <module>
    _oalib = swig_import_helper()
  File "/usr/lib64/python2.6/site-packages/oalib.py", line 24, in swig_import_helper
    _mod = imp.load_module('_oalib', fp, pathname, description)
ImportError: /usr/lib64/python2.6/site-packages/_oalib.so: undefined symbol: gzopen

**Comment by eendebakpt** [comment]
It seems zlib is not linked properly to the shared library. Have you installed zlib? On CentOs this should be something like: 

> yum install zlib-devel
> yum install zlib-devel.x86_64

I also updated the build scripts to check for zlib. Can you compile from the latest version from github and send me the complete output from python setup.py build?

**Comment by ohfang** [comment]
It works now! Thanks!
And by the way, I did install zlib-devel, otherwise it won't build. The problem occurred when I "import oalib" in python. But your update has solved it. I download the latest github version, and it can build and install and import.

The output of python setup.py build: 

find_packages: ['oapackage']
running build
running build_py
file oalib.py (for module oalib) not found
creating build
creating build/lib.linux-x86_64-2.6
creating build/lib.linux-x86_64-2.6/oapackage
copying oapackage/oahelper.py -> build/lib.linux-x86_64-2.6/oapackage
copying oapackage/graphtools.py -> build/lib.linux-x86_64-2.6/oapackage
copying oapackage/scanf.py -> build/lib.linux-x86_64-2.6/oapackage
copying oapackage/__init__.py -> build/lib.linux-x86_64-2.6/oapackage
copying oapackage/Doptim.py -> build/lib.linux-x86_64-2.6/oapackage
copying oapackage/markup.py -> build/lib.linux-x86_64-2.6/oapackage
file oalib.py (for module oalib) not found
running build_ext
building '_oalib' extension
swigging oalib.i to oalib_wrap.cpp
swig -python -modern -c++ -w503,401,362,302,389,446,509,305 -Isrc/ -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -o oalib_wrap.cpp oalib.i
src//lmc.h:524: Warning(312): Nested class not currently supported (ignored).
src//arraytools.h:99: Warning(472): Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
src//arraytools.h:99: Warning(472): Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
src//arraytools.h:99: Warning(472): Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/src
creating build/temp.linux-x86_64-2.6/src/bitarray
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c oalib_wrap.cpp -o build/temp.linux-x86_64-2.6/oalib_wrap.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from oalib_wrap.cpp:3270:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
oalib_wrap.cpp: In function ‘PyObject* _wrap_print_fracs(PyObject*, PyObject*)’:
oalib_wrap.cpp:54103: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_get_time_ms(PyObject*, PyObject*)’:
oalib_wrap.cpp:37164: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_print_options(PyObject*, PyObject*)’:
oalib_wrap.cpp:19253: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_new_OAextend(PyObject*, PyObject*)’:
oalib_wrap.cpp:43411: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_new_arraysymmetry(PyObject*, PyObject*)’:
oalib_wrap.cpp:48236: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_new_LMCreduction_t(PyObject*, PyObject*)’:
oalib_wrap.cpp:49545: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_new_array_transformation_t(PyObject*, PyObject*)’:
oalib_wrap.cpp:30806: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_arrayfile_t_arrayNbits(PyObject*, PyObject*)’:
oalib_wrap.cpp:33736: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_oa_file_exists(PyObject*, PyObject*)’:
oalib_wrap.cpp:23064: 警告：此函数中的‘argv[0]’在使用前可能未初始化
oalib_wrap.cpp: In function ‘PyObject* _wrap_file_exists(PyObject*, PyObject*)’:
oalib_wrap.cpp:22979: 警告：此函数中的‘argv[0]’在使用前可能未初始化
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/Deff.cpp -o build/temp.linux-x86_64-2.6/src/Deff.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/Deff.cpp:8:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/arrayproperties.cpp -o build/temp.linux-x86_64-2.6/src/arrayproperties.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/tools.h:49,
                 from src/arrayproperties.cpp:20:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/arraytools.cpp -o build/temp.linux-x86_64-2.6/src/arraytools.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/arraytools.cpp:5:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp: In member function ‘void arrayfile::arrayfile_t::append_array(const array_link&, int)’:
src/arraytools.cpp:3092: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp: In member function ‘void arrayfile::arrayfile_t::writeheader()’:
src/arraytools.cpp:3408: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3409: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3410: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3411: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3412: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3424: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3426: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp:3427: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp: In member function ‘void arrayfile::arrayfile_t::write_array_binary(const carray_t*, int, int)’:
src/arraytools.cpp:4245: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp: In function ‘void writeblob(const TypeIn*, int, FILE*) [with TypeIn = short int, TypeOut = char]’:
src/arraytools.cpp:4226:   instantiated from here
src/arraytools.cpp:2948: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.cpp: In function ‘void writeblob(const TypeIn*, int, FILE*) [with TypeIn = short int, TypeOut = int]’:
src/arraytools.cpp:4229:   instantiated from here
src/arraytools.cpp:2948: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/bitarray/bit_array.cpp -o build/temp.linux-x86_64-2.6/src/bitarray/bit_array.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/extend.cpp -o build/temp.linux-x86_64-2.6/src/extend.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/extend.h:13,
                 from src/extend.cpp:23:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/lmc.cpp -o build/temp.linux-x86_64-2.6/src/lmc.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/lmc.cpp:5:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/mathtools.cpp -o build/temp.linux-x86_64-2.6/src/mathtools.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/md5.cpp -o build/temp.linux-x86_64-2.6/src/md5.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/nonroot.cpp -o build/temp.linux-x86_64-2.6/src/nonroot.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/tools.h:49,
                 from src/nonroot.h:19,
                 from src/nonroot.cpp:5:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/oaoptions.cpp -o build/temp.linux-x86_64-2.6/src/oaoptions.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/oaoptions.cpp:9:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/pareto.cpp -o build/temp.linux-x86_64-2.6/src/pareto.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/strength.cpp -o build/temp.linux-x86_64-2.6/src/strength.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/tools.h:49,
                 from src/strength.h:12,
                 from src/strength.cpp:14:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -Isrc -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include/python2.6 -c src/tools.cpp -o build/temp.linux-x86_64-2.6/src/tools.o -DSWIGCODE -DFULLPACKAGE -DNOOMP -DUSEZLIB -O2 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC
In file included from src/tools.h:49,
                 from src/tools.cpp:25:
src/arraytools.h: In function ‘void writebinheader(FILE*, int, int)’:
src/arraytools.h:1771: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
src/arraytools.h: In function ‘void vectorvector2binfile(std::string, std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, int, int)’:
src/arraytools.h:1821: 警告：忽略声明有 warn_unused_result 属性的‘size_t fwrite(const void*, size_t, size_t, FILE*)’的返回值
At global scope:
cc1plus: 警告：无法识别的命令行选项“-Wno-unused-result”
g++ -pthread -shared build/temp.linux-x86_64-2.6/oalib_wrap.o build/temp.linux-x86_64-2.6/src/Deff.o build/temp.linux-x86_64-2.6/src/arrayproperties.o build/temp.linux-x86_64-2.6/src/arraytools.o build/temp.linux-x86_64-2.6/src/bitarray/bit_array.o build/temp.linux-x86_64-2.6/src/extend.o build/temp.linux-x86_64-2.6/src/lmc.o build/temp.linux-x86_64-2.6/src/mathtools.o build/temp.linux-x86_64-2.6/src/md5.o build/temp.linux-x86_64-2.6/src/nonroot.o build/temp.linux-x86_64-2.6/src/oaoptions.o build/temp.linux-x86_64-2.6/src/pareto.o build/temp.linux-x86_64-2.6/src/strength.o build/temp.linux-x86_64-2.6/src/tools.o -L/usr/lib64 -lpython2.6 -o build/lib.linux-x86_64-2.6/_oalib.so -lz
running build_scripts
creating build/scripts-2.6
copying and adjusting scripts/example_python_testing.py -> build/scripts-2.6
changing mode of build/scripts-2.6/example_python_testing.py from 644 to 755
