### ISSUE TITLE
signature of conference_t ? Use of sphinx-doctest ?

### ISSUE THREAD

**Issue by gsagnol** [eendebakpt/oapackage#102]
`ctype=oapackage.conference_t(N=8, k=8)` raises an error
`TypeError: __init__() got an unexpected keyword argument 'k'`
but the statement `ctype=oapackage.conference_t(8,8,0)` seems to be working.

I tried to reproduce your example in the section Generation of designs -> Conference designs, but it is not working. I would strongly recommend that you use sphinx-doctest, in addition to your unit tests, to automatically check that the examples of the documentation work as expected. For example, in the documentation, your code includes a line
`>>> al.showarray() array: 0 1 1 1 0 -1 1 1 0 1 1 1 1 1 -1 1 -1 1 1 -1 1 1 -1 -1`
This is clearly wrong, and has been manually entered rather than generated by sphinx, because this is an output string (which should not start with ">>>"m and,  new lines "\" are missing.

**Comment by eendebakpt** [comment]
@gsagnol The use of keyword arguments is a little bit hard over different versions of python/swig. I updated the example to use the version without keyword arguments.

I didn't know about `sphinx-doctest`, thanks for the suggestion! I started using it, except for the examples where the algorithm uses random numbers and the output is not exactly reproducable.

**Comment by gsagnol** [comment]
For sphinx-doctest, you could also seed the random number generator (cf. `np.random.seed`) so the output is reproducible.)
