### ISSUE TITLE
Wrong numbers of factors in tutorial

### ISSUE THREAD

**Issue by gsagnol** [eendebakpt/oapackage#172]
In this tutorial on generating D-efficient orthogonal arrays,
https://oapackage.readthedocs.io/en/latest/examples/example_optimal_orthogonal_arrays.html

after cell [10], you claim to generate a design in OA(32, 2, 2^7) , but the displayed array only has 5 factors.

**Comment by eendebakpt** [comment]
@gsagnol Thanks for reporting
