### ISSUE TITLE
Calculating Pareto Set with Minimizing an Objective 

### ISSUE THREAD

**Issue by smiret** [eendebakpt/oapackage#184]
Your example for calculating a [Pareto optimal set](https://oapackage.readthedocs.io/en/latest/examples/example_pareto.html) was useful. I was wondering if your package allows the following:

1. Calculating a Pareto optimal set when minimizing one/more objective? (Meaning I want to maximize objective 1 and minimize objective 2, etc) If so, could you provide an example?
2. Does your package support calculating the hypervolume of a Pareto set? If so, do you more details on the methods that you are using for that and a potential example?

Currently it's possible to "hack" the question in 1 by doing data manipulating of the objective data, such that the objectives end up going from 0 to 1 and each "normalized objective" is being maximized, but it would be useful if one could specify minimization and maximization on the various objective on the raw data directly. Appreciate any thoughts/discussion on this and thanks for putting the package together!

**Comment by eendebakpt** [comment]
@smiret

1. The Pareto class from the oapackage always maximizes the values. So if you want to minimize an objective you can (as you write) normalize the data by adding a minus sign.
There is an option for multi-values objects to reverse the normal sort order (left to right), to the other order (right to left). See https://oapackage.readthedocs.io/en/latest/oalib.html?highlight=multi#oalib.mvalue_t_long. But this is different from what you want I think.
I agree that having an option to specify minimization or maximization would be convenient, but this is not something I will add to the package myself.
2. Calculating the hypervolume is not included in the package.
