### ISSUE TITLE
Modifying Nauty to Support Directed Graphs

### ISSUE THREAD

**Issue by nada-hammad** [eendebakpt/oapackage#187]
Hello,

I'm trying to modify the source code to support directed graphs. 

To do this, I modified the `reduceNauty` function to use `DEFAULTOPTIONS_DIGRAPH` instead of `DEFAULTOPTIONS_GRAPH`, and I set `options.digraph` to true if the input graph is not symmetric. I also imported `nautinv.h` because `DEFAULTOPTIONS_DIGRAPH` uses the function `adjacencies` which is declared there.
<img width="740" alt="Screen Shot 2021-01-13 at 2 52 46 PM" src="https://user-images.githubusercontent.com/25358311/104454813-141cc680-55af-11eb-88f7-b86ec075b9a8.png">

Then I tried to test this using the example outlined [here](https://oapackage.readthedocs.io/en/latest/examples/example_nauty.html), but without making the input array symmetric. However, the reduced array of the original graph and that of the permuted graph are not always equal.

Any idea what I'm missing/doing wrong?
Thanks!

**Comment by eendebakpt** [comment]
@nada-hammad Have you make progress with this already? If not, then I will have a look this week

**Comment by nada-hammad** [comment]
@eendebakpt Haven't made progress, but we've since moved on to a different approach that doesn't use this package, so this doesn't require immediate attention. Thank you!

**Comment by eendebakpt** [comment]
@nada-hammad Ok thanks. PR #194 should make calculations with directed graphs possible. Closing this issue.
