### ISSUE TITLE
pip install fails on CentOS

### ISSUE THREAD

**Issue by goncaloperes** [eendebakpt/oapackage#188]
When installing `OApackage` on a CentOS 7 machine in conda with

    pip install OApackage

Or

    pip install git+https://github.com/eendebakpt/oapackage.git

It fails giving the following error

    ERROR: Command errored out with exit status 1:
         command: /home/hpc/goperes/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z0pcwye/OApackage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z0pcwye/OApackage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pzt4_zdf
             cwd: /tmp/pip-install-6z0pcwye/OApackage/
        Complete output (10 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-6z0pcwye/OApackage/setup.py", line 331, in <module>
            raise Exception('could not find a recent version if SWIG')
        Exception: could not find a recent version if SWIG
        swig_version 2.0.10, swig_executable None
        old version of setuptools: 49.2.0.post20200714
        Readthedocs environment: False
        checkZlib: compile and link
        find_packages: ['oapackage', 'tests']
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by salvoc81** [comment]
@goncaloperes I had the same problem and it was solved by installing `SWING` using the package manager in my OS (Arch Linux).

**Comment by eendebakpt** [comment]
@goncaloperes Did you solve the problem already? swig requires a minimum version of 3.2, and your system seems to have swig 2.0.10 installed
