### ISSUE TITLE
How to get an array by row number, column number and level number? 

### ISSUE THREAD

**Issue by ohfang** [eendebakpt/oapackage#2]

**Comment by eendebakpt** [comment]
What do you mean by getting an array? Do you mean enumeration of series of orthogonal arrays?

**Comment by ohfang** [comment]
yes. I am working on an application that help users design experiments. Users enter factor number and level number of each factor, then the application automatically prints an appropriate table.

**Comment by eendebakpt** [comment]
You have two options with the software: generate orthogonal arrays or D-optimal arrays. The orthogonal arrays are generated column by column. For example:

``` python
import oapackage
k=6
s=2
N=24
strength=2
r = oapackage.runExtend(N, k, strength, s, verbose=1)    
print('found %d arrays' % (len(r)))
```

Note that for large values of N or k the program might take too much time or memory to complete.

The D-optimal arrays can be generated at once:

``` python
import oapackage

k=6
s=2
N=16
strength=2
arrayclass=oapackage.arraydata_t(s, N, strength, k)

score, dds, lst, _=oapackage.Doptimize(arrayclass, 1, optimfunc=[1,0,0], verbose=1 )
lst[0].showarray()
```

**Comment by WhatAShot** [comment]
Hi, I run the codes, and get

`TypeError: Doptimize() got an unexpected keyword argument 'optimfunc'`
