### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by PLisi97** [eendebakpt/oapackage#209]
Hello.

I used the command `pip install OApackage`, but I get the error:
```
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.7/dist-packages (from OApackage) (1.21.5)
Building wheels for collected packages: OApackage
  Building wheel for OApackage (setup.py) ... error
  ERROR: Failed building wheel for OApackage
  Running setup.py clean for OApackage
Failed to build OApackage
Installing collected packages: OApackage
    Running setup.py install for OApackage ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ki2bmvp2/oapackage_6bfc808dbc024485997027785668713d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ki2bmvp2/oapackage_6bfc808dbc024485997027785668713d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ul1fmmec/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/OApackage Check the logs for full command output.
```

How can I solve this, please?

**Comment by ngctnnnn** [comment]
Same problem for me

**Comment by PLisi97** [comment]
> Same problem for me

The solution suggested by the author is:

!apt install swig
!pip install -v oapackage

The oapackage requires swig 3.x, but this is not available by default on colab. The proposed code don't get you the latest version of oapackage, but it get you a version running.

**Comment by ngctnnnn** [comment]
> > Same problem for me
> 
> The solution suggested by the author is:
> 
> !apt install swig !pip install -v oapackage
> 
> The oapackage requires swig 3.x, but this is not available by default on colab. The proposed code don't get you the latest version of oapackage, but it get you a version running.

Thanks a lot ! I have succeeded importing it on colab.

**Comment by eendebakpt** [comment]
Thanks for reporting, closing the issue.
