### ISSUE TITLE
Pareto Front for Object with Attributes

### ISSUE THREAD

**Issue by puyuanliu** [eendebakpt/oapackage#213]
Is it possible for me to maintain a set of object based on the value of their attributes? e.g., Pareto Frong of a set of people based on their age and salary. but these people have name and id as well.

**Comment by eendebakpt** [comment]
@puyuanliu The current implementation of the Pareto objects (either from C++ or from Python) only deals with a single type to compare (see https://github.com/eendebakpt/pareto/blob/master/pareto.h#L86). So mixing types such as age (float) and name (string) is not possible. You could only use the float attributes and keep track of the others using the index.

But I would recommand to write your own Pareto implementation is python, that is probably faster and more convenient.
