### ISSUE TITLE
pip install error on macOS Monterey

### ISSUE THREAD

**Issue by Rhexos** [eendebakpt/oapackage#224]
I've tried 
```
pip install oapackage
```
and
```
pip install git+https://github.com/eendebakpt/oapackage.git
```
it fails giving this error on swig 3.x
```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-install-2ephibt3/oapackage_1d028f485cdf4b28bf35e30b37c674ee/setup.py:128: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(swig_version) >= LooseVersion(swig_minimum_version):
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-install-2ephibt3/oapackage_1d028f485cdf4b28bf35e30b37c674ee/setup.py", line 297, in <module>
          raise Exception('could not find a recent version if SWIG')
      Exception: could not find a recent version if SWIG
      swig_version 3.0.12, swig_executable None
      Readthedocs environment: False
      checkZlib: compile and link
      find_packages: ['oapackage', 'tests']
      [end of output]
```
if i use the second command, i get an error with numpy although it's installed and updated

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 22, in <module>
      ModuleNotFoundError: No module named 'numpy'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/rditljp7/anaconda3/envs/theia/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/rditljp7/anaconda3/envs/theia/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/rditljp7/anaconda3/envs/theia/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-build-env-ppwbs7dx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-build-env-ppwbs7dx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-build-env-ppwbs7dx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/pip-build-env-ppwbs7dx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      RuntimeError: numpy cannot be imported. numpy must be installed prior to installing OApackage
      [end of output]
```

**Comment by ABohynDOE** [comment]
For the first error, it looks like SWIG is not installed on your machine.
For the second one, you first need to install `numpy` in your python environment before installing the OApackage.

**Comment by Rhexos** [comment]
> For the first error, it looks like SWIG is not installed on your machine. For the second one, you first need to install `numpy` in your python environment before installing the OApackage.

First error, I have a SWIG 3.x installed, if updated to 4.x it gives me a long error. 

'''
fatal error: too many errors emitted, stopping now [-ferror-limit=]
      25 warnings and 20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
'''

For the second error, I have numpy installed in the environment, but for some reason it doesn't think so. I've double-triple checked.

**Comment by ABohynDOE** [comment]
For the SWIG problem, it looks like it doesn't come from the OApackage itself but from the SWIG installation on your machine. Maybe try uninstalling and re-installing it.
For the `numpy` problem, I think it might get solved when OApackage is installed but otherwise I would suggest testing it in a new virtual environment where you have nothing installed and then add `numpy` and then try again.
Something like:
```
python3 -m venv new-env
source new-env/bin/activate
pip install numpy 
pip install oapackage
```

**Comment by Rhexos** [comment]
i've uninstalled and reinstalled numerous times, but attempting in a clean environment lead me to a new error. first part of it says zlib missing, but continues and faults at a gcc error.

```
  × Running setup.py install for oapackage did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      swig_version 4.1.1, swig_executable /Users/rditljp7/new-env/bin/swig
      Readthedocs environment: False
      checkZlib: compile and link
      In file included from /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/syslimits.h:7,
                       from /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/limits.h:34,
                       from /Users/rditljp7/anaconda3/include/zconf.h:418,
                       from /Users/rditljp7/anaconda3/include/zlib.h:34,
                       from /var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/helloztest_l_z2nxvq/helloz.c:2:
      /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/limits.h:203:75: error: no include path in which to search for limits.h
        203 | #include_next <limits.h>                /* recurse down to the real one */
            |                                                                           ^
      /Users/rditljp7/anaconda3/include/zconf.h:444:14: fatal error: sys/types.h: No such file or directory
        444 | #    include <sys/types.h>      /* for off_t */
            |              ^~~~~~~~~~~~~
      compilation terminated.
      checkZlib: compile error in /var/folders/d1/07g2xmk94537h_r75myxc9fdm40xwb/T/helloztest_l_z2nxvq/helloz.c, zlib not available
      find_packages: ['oapackage', 'tests']
      OApackage: version 2.7.6
      running install
      running build_ext
      building '_oalib' extension
      swigging oalib.i to oalib_wrap.cpp
      /Users/rditljp7/new-env/bin/swig -python -c++ -doxygen -w503,401,362,302,389,446,509,305 -Isrc/ -DSWIGCODE -DFULLPACKAGE -Isrc/nauty/ -DNOOMP -DNOZLIB -o oalib_wrap.cpp oalib.i
      src/arraytools.h:89: Warning 472: Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
      src/arraytools.h:89: Warning 472: Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
      src/arraytools.h:89: Warning 472: Overloaded method eigenInfo(MatrixFloat const) with no explicit typecheck typemap for arg 0 of type 'MatrixFloat const'
      /Users/rditljp7/new-env/lib/python3.8/site-packages/swig/data/share/swig/4.1.1/std/std_pair.i:37: Warning 472: Overloaded method std::pair< MatrixFloat,MatrixFloat >::pair(std::pair< MatrixFloat,MatrixFloat > const &) with no explicit typecheck typemap for arg 0 of type 'Eigen::MatrixXd'
      /Users/rditljp7/new-env/lib/python3.8/site-packages/swig/data/share/swig/4.1.1/std/std_pair.i:37: Warning 472: Overloaded method std::pair< MatrixFloat,MatrixFloat >::pair(std::pair< MatrixFloat,MatrixFloat > const &) with no explicit typecheck typemap for arg 1 of type 'Eigen::MatrixXd'
      creating build
      creating build/temp.macosx-10.9-x86_64-3.8
      creating build/temp.macosx-10.9-x86_64-3.8/src
      creating build/temp.macosx-10.9-x86_64-3.8/src/bitarray
      creating build/temp.macosx-10.9-x86_64-3.8/src/nauty
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/rditljp7/anaconda3/include -arch x86_64 -I/Users/rditljp7/anaconda3/include -arch x86_64 -I. -Isrc -I/Users/rditljp7/new-env/lib/python3.8/site-packages/numpy/core/include -I/Users/rditljp7/new-env/include -I/Users/rditljp7/anaconda3/include/python3.8 -c oalib_wrap.cpp -o build/temp.macosx-10.9-x86_64-3.8/oalib_wrap.o -DSWIGCODE -DFULLPACKAGE -Isrc/nauty/ -DNOOMP -DNOZLIB -O3 -Wno-unknown-pragmas -Wno-sign-compare -Wno-return-type -Wno-unused-variable -Wno-unused-result -fPIC -Wno-date-time
      cc1plus: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
      In file included from /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/syslimits.h:7,
                       from /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/limits.h:34,
                       from /Users/rditljp7/anaconda3/include/python3.8/Python.h:11,
                       from oalib_wrap.cpp:168:
      /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/limits.h:203:75: error: no include path in which to search for limits.h
        203 | #include_next <limits.h>                /* recurse down to the real one */
            |                                                                           ^
      In file included from /Users/rditljp7/anaconda3/include/python3.8/Python.h:25:
      /usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/12/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
         78 | #include <_stdio.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
```

**Comment by ABohynDOE** [comment]
I'm personally using SWIG 4.0.1 on linux and I've installed version 2.7.1 of the OApackage, maybe try with these versions to see if the latest version of SWIG is the problem ?

**Comment by eendebakpt** [comment]
@ABohynDOE @Rhexos Missing zlib is not a problem in general. You won't be able to read compressed data files, but all other functionality will work.

The gcc error looks like a problem with the compiler chain, but not related specifically to oapackage. Headers like `stdio.h` and `limits.h` should be available on any system offering a c++ compiler.

When I google on the error, I find several related topics. E.g. https://github.com/Microsoft/LightGBM/issues/1420. Can you the suggestions from there?

**Comment by sebhaan** [comment]
any update on this? Still fails to install on Mac m1/m2 using latest OApackage version 2.7.8 (tested with swig 3/swig 4 and numpy preinstalled in new env).

**Comment by eendebakpt** [comment]
@sebhaan Can you send me the exact error message you get?

**Comment by GeoMattB** [comment]
does this do anything? 
pip install oapackage --use-pep517

**Comment by sebhaan** [comment]
> does this do anything? pip install oapackage --use-pep517

Nope

**Comment by sebhaan** [comment]
> @sebhaan Can you send me the exact error message you get?

@eendebakpt attached is the complete error msg.
[Errormessage_OApackage.txt](https://github.com/eendebakpt/oapackage/files/12704914/Errormessage_OApackage.txt)

**Comment by eendebakpt** [comment]
> > @sebhaan Can you send me the exact error message you get?
> 
> @eendebakpt attached is the complete error msg. [Errormessage_OApackage.txt](https://github.com/eendebakpt/oapackage/files/12704914/Errormessage_OApackage.txt)

The main issue seems related to https://stackoverflow.com/questions/42941502/how-to-compile-c-on-mac-os-using-tr1. The output if swig (e.g. `oalib_wrap.cpp`) contains a line `result = (bool)valid_ptr((std::tr1::shared_ptr< symmdata > const &)*arg1);` with `std::tr1` which is no longer supported (by default).

@sebhaan Can you post the version of swig you are using (e.g. `swig -version`) and can you also post the output of `pip -v install oapackage`? I am not yet sure how to let swig generate the correct code.

**Comment by sebhaan** [comment]
> > > @sebhaan Can you send me the exact error message you get?
> > 
> > 
> > @eendebakpt attached is the complete error msg. [Errormessage_OApackage.txt](https://github.com/eendebakpt/oapackage/files/12704914/Errormessage_OApackage.txt)
> 
> The main issue seems related to https://stackoverflow.com/questions/42941502/how-to-compile-c-on-mac-os-using-tr1. The output if swig (e.g. `oalib_wrap.cpp`) contains a line `result = (bool)valid_ptr((std::tr1::shared_ptr< symmdata > const &)*arg1);` with `std::tr1` which is no longer supported (by default).
> 
> @sebhaan Can you post the version of swig you are using (e.g. `swig -version`) and can you also post the output of `pip -v install oapackage`? I am not yet sure how to let swig generate the correct code.

@eendebakpt 
thanks for checking.

The swig version is: SWIG Version 4.1.1 - Compiled with clang++ [aarch64-apple-darwin22.1.0]

The output of `pip -v install oapackage` is attached in 
[install_error.txt](https://github.com/eendebakpt/oapackage/files/12721709/install_error.txt)

**Comment by eendebakpt** [comment]
@sebhaan Can you try `pip install git+https://github.com/eendebakpt/oapackage@tr1`?

It seems that on your platform https://github.com/eendebakpt/oapackage/blob/dev/src/lmc.h#L289 is included in the compilation, even though you are on mac and the section is guarded by `__APPLE__`

**Comment by sebhaan** [comment]
> @sebhaan Can you try `pip install git+https://github.com/eendebakpt/oapackage@tr1`?
> 
> It seems that on your platform https://github.com/eendebakpt/oapackage/blob/dev/src/lmc.h#L289 is included in the compilation, even though you are on mac and the section is guarded by `__APPLE__`

thanks @eendebakpt , unfortunately still fails to install (see error msg attached). 
[stderr_oapackage@tr1.txt](https://github.com/eendebakpt/oapackage/files/12745369/stderr_oapackage%40tr1.txt)

**Comment by sebhaan** [comment]
> @sebhaan Can you try `pip install git+https://github.com/eendebakpt/oapackage@tr1` once more? I addressed the issues from the previous attempt.

@eendebakpt thanks for your help. Unfortunately it's still not working. 
[stderr_oapackage@tr1_2.txt](https://github.com/eendebakpt/oapackage/files/12754058/stderr_oapackage%40tr1_2.txt)

**Comment by eendebakpt** [comment]
@sebhaan Could you try `pip install oapackage==2.7.10`?

**Comment by sebhaan** [comment]
> @sebhaan Could you try `pip install oapackage==2.7.10`?

@eendebakpt same problem 
[stderr_oapackage2.7.10.txt](https://github.com/eendebakpt/oapackage/files/12762706/stderr_oapackage2.7.10.txt)

**Comment by eendebakpt** [comment]
@sebhaan For some reason the compiler you are using is very picky on the enums. The code it is failing on has worked for many years on both windows and linux. Searching for the specific error message does not yield any usefull results. I have 3 more variations for you to test out:
```
pip install git+https://github.com/eendebakpt/oapackage@enum
pip install git+https://github.com/eendebakpt/oapackage@enum2
pip install git+https://github.com/eendebakpt/oapackage@enum3
```

Do you have the option to download the source code for the oapackage and build the executables (so not the python package)?  The commands for building the executable are 
```
$ mkdir -p build; cd build
$ cmake ..
$ make
```

**Comment by sebhaan** [comment]
> @sebhaan For some reason the compiler you are using is very picky on the enums. The code it is failing on has worked for many years on both windows and linux. Searching for the specific error message does not yield any usefull results. I have 3 more variations for you to test out:
> 
> ```
> pip install git+https://github.com/eendebakpt/oapackage@enum
> pip install git+https://github.com/eendebakpt/oapackage@enum2
> pip install git+https://github.com/eendebakpt/oapackage@enum3
> ```
> 
> Do you have the option to download the source code for the oapackage and build the executables (so not the python package)? The commands for building the executable are
> 
> ```
> $ mkdir -p build; cd build
> $ cmake ..
> $ make
> ```

@eendebakpt  Tested the install of the three enum version but all three failed (below the install errors). The cmake compile works fine and shows only a couple of deprecated warnings with C++17.

[out_cmake.txt](https://github.com/eendebakpt/oapackage/files/12797613/out_cmake.txt)
[stderr_oapackage_enum.txt](https://github.com/eendebakpt/oapackage/files/12797623/stderr_oapackage_enum.txt)
[stderr_oapackage_enum2.txt](h
[stderr_oapackage_enum3.txt](https://github.com/eendebakpt/oapackage/files/12797629/stderr_oapackage_enum3.txt)
ttps://github.com/eendebakpt/oapackage/files/12797626/stderr_oapackage_enum2.txt)

**Comment by eendebakpt** [comment]
@sebhaan Thanks for all the testing! We are making progress, the amount of errors has been reduced a lot already. Can you test `pip install git+https://github.com/eendebakpt/oapackage@v2711`?

In the near future we will have to move to a new build system (since python 3.12 is released), perhaps than we can ensure that the c++ build and python build use the same compiler (and same compiler settings).

**Comment by sebhaan** [comment]
> @sebhaan Thanks for all the testing! We are making progress, the amount of errors has been reduced a lot already. Can you test `pip install git+https://github.com/eendebakpt/oapackage@v2711`?
> 
> In the near future we will have to move to a new build system (since python 3.12 is released), perhaps than we can ensure that the c++ build and python build use the same compiler (and same compiler settings).

@eendebakpt Happy to help. Below the install errror for v2711 
[stderr_oapackage_v2711.txt](https://github.com/eendebakpt/oapackage/files/12809026/stderr_oapackage_v2711.txt)

**Comment by eendebakpt** [comment]
@sebhaan Can you try `pip install git+https://github.com/eendebakpt/oapackage@v2711`?

**Comment by sebhaan** [comment]
> @sebhaan Can you try `pip install git+https://github.com/eendebakpt/oapackage@dev`?

@eendebakpt You did it! "Successfully installed OApackage-2.7.11" Can confirm now that both, @dev and @v2711, successfully install on Mac M1 (below install output for some remaining warnings). Well done, big thanks! 
[stdout_oapackage_dev_successfull.txt](https://github.com/eendebakpt/oapackage/files/12825279/stdout_oapackage_dev_successfull.txt)

**Comment by eendebakpt** [comment]
Nice! The package has been updated on PyPi
