### ISSUE TITLE
Cannot install on M2 Mac. ModuleNotFoundError: No module named 'swig'

### ISSUE THREAD

**Issue by njusu** [eendebakpt/oapackage#248]
Hi there, I'm trying to install OApackage on my M2 mac but was unable to install due to this error when build. I've tried few times and also tried the commands in this issue: https://github.com/eendebakpt/oapackage/issues/224. Could you help with that? Thanks!

```
/export/apps/python/3.10/bin/python3 -m venv py310
source py310/bin/activate
pip install numpy==1.24.4
pip install swig==4.1.1
pip install OApackage==2.7.11 --log oa_clean_install.txt
```
[oa_clean_install.txt](https://github.com/eendebakpt/oapackage/files/13077717/oa_clean_install.txt)

Here is a copy of the log.

**Comment by yenchunliu97** [comment]
Same error on M1 Mac.

**Comment by yenchunliu97** [comment]
solved! it works with python 3.9 (can't work with python 3.10)

**Comment by eendebakpt** [comment]
> ```
> pip install OApackage==2.7.11 --log oa_clean_install.txt
> ```

@njusu There seems to be a problem with your swig installation. Could you try:
```
python -m pip install swig==4.1.1
python -m pip install OApackage==2.7.11 --log oa_clean_install.txt
```
(to be sure the pip is from the virtual environment)

Also try from the command line:
```
swig -version
```
That command should succeed. If not, then the swig installation is broken.

**Comment by njusu** [comment]
> solved! it works with python 3.9 (can't work with python 3.10)

Unfortunately it failed on python 3.9.5 for the same error for me.

**Comment by njusu** [comment]
@eendebakpt Thank you for helping. I checked my previous venv, and `which pip` shows the one in my venv, I also checked `swig -version`:
```
$ which pip
/Users/ysu1/py39/bin/pip

$ swig -version

SWIG Version 4.1.1

Compiled with /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ [Darwin]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information
``` 

I created a new venv and use the `python -m pip` as suggested, and got the same error.

**Comment by eendebakpt** [comment]
@njusu Could you try to update pip and install the wheel package?
```
python -m pip install --upgrade pip
pip install wheel
```
And then try to install the OApackage again. Not sure whether that will resolve the issue, since the main error message is about swig.

**Comment by eendebakpt** [comment]
And could you also try the following?
```
pip install git+https://github.com/eendebakpt/oapackage@tt
```

**Comment by njusu** [comment]
> @njusu Could you try to update pip and install the wheel package?
> 
> ```
> python -m pip install --upgrade pip
> pip install wheel
> ```
> 
> And then try to install the OApackage again. Not sure whether that will resolve the issue, since the main error message is about swig.

Unfortunately it's still giving the same error after upgrading pip and installing wheel, but the other link you shared workd!

**Comment by njusu** [comment]
> And could you also try the following?
> 
> ```
> pip install git+https://github.com/eendebakpt/oapackage@tt
> ```

@eendebakpt Wow great, this worked! Thanks so much!
