### ISSUE TITLE
a little mistake when using symmetry_group init()

### ISSUE THREAD

**Issue by MeredithChai** [eendebakpt/oapackage#257]
https://github.com/eendebakpt/oapackage/blob/dd13d87e5472da993db06ddec2e5aa42d444cebc/src/mathtools.cpp#L50
here the logic may be:
```if (!is.issorteddescending()) {```

**Comment by eendebakpt** [comment]
@MeredithChai You are right, this should indeed be `issorteddescending`. How did you find the issue? It is not in the actual computation, but only in the debugging output.
