### ISSUE TITLE
Generation of series

### ISSUE THREAD

**Issue by AntonGitName** [eendebakpt/oapackage#6]
Hi, @eendebakpt 

Thank you for a great project.

I found your repository across the web and tried it to generate an array for OA(90; 3; 5<sup>1</sup>3<sup>2</sup>2<sup>1</sup>) just like you did [here](http://pietereendebak.nl/oapackage/series/series-90.5-3-3-2-t3.html).

Unfortunately, I failed to reproduce the series and I do not really understand the results I got.

So, here is the code I tried:
```
    std::vector<int> s;
    s.push_back(5);
    s.push_back(3);
    s.push_back(3);
    s.push_back(2);
//  auto s = {5, 3, 3, 2};
    arraydata_t adata(s, 90, 3, 4);
    array_link al(adata.N, adata.strength, 1);
    al.create_root(adata);
    auto t = extend_array(al, adata);
    auto result = t[0];

    auto reduced = result.reduceLMC();
    std::cout << reduced;
```
The output:
`Found 21046 arrays in total, only 39 in LMC form, total is 39`
<details>
<summary>OA: Click to expand</summary>
  0   0   0   0 <br>
  0   0   0   0 <br>
  0   0   1   0 <br>
  0   0   1   1 <br>
  0   0   2   1 <br>
  0   0   2   1 <br>
  0   1   0   0 <br>
  0   1   0   1 <br>
  0   1   1   0 <br>
  0   1   1   1 <br>
  0   1   2   0 <br>
  0   1   2   1 <br>
  0   2   0   1 <br>
  0   2   0   1 <br>
  0   2   1   0 <br>
  0   2   1   1 <br>
  0   2   2   0 <br>
  0   2   2   0 <br>
  1   0   0   0 <br>
  1   0   0   0 <br>
  1   0   1   0 <br>
  1   0   1   1 <br>
  1   0   2   1 <br>
  1   0   2   1 <br>
  1   1   0   0 <br>
  1   1   0   1 <br>
  1   1   1   0 <br>
  1   1   1   1 <br>
  1   1   2   0 <br>
  1   1   2   1 <br>
  1   2   0   1 <br>
  1   2   0   1 <br>
  1   2   1   0 <br>
  1   2   1   1 <br>
  1   2   2   0 <br>
  1   2   2   0 <br>
  2   0   0   0 <br>
  2   0   0   1 <br>
  2   0   1   0 <br>
  2   0   1   1 <br>
  2   0   2   0 <br>
  2   0   2   1 <br>
  2   1   0   0 <br>
  2   1   0   1 <br>
  2   1   1   0 <br>
  2   1   1   1 <br>
  2   1   2   0 <br>
  2   1   2   1 <br>
  2   2   0   0 <br>
  2   2   0   1 <br>
  2   2   1   0 <br>
  2   2   1   1 <br>
  2   2   2   0 <br>
  2   2   2   1 <br>
  3   0   0   1 <br>
  3   0   0   1 <br>
  3   0   1   0 <br>
  3   0   1   1 <br>
  3   0   2   0 <br>
  3   0   2   0 <br>
  3   1   0   0 <br>
  3   1   0   1 <br>
  3   1   1   0 <br>
  3   1   1   1 <br>
  3   1   2   0 <br>
  3   1   2   1 <br>
  3   2   0   0 <br>
  3   2   0   0 <br>
  3   2   1   0 <br>
  3   2   1   1 <br>
  3   2   2   1 <br>
  3   2   2   1 <br>
  4   0   0   1 <br>
  4   0   0   1 <br>
  4   0   1   0 <br>
  4   0   1   1 <br>
  4   0   2   0 <br>
  4   0   2   0 <br>
  4   1   0   0 <br>
  4   1   0   1 <br>
  4   1   1   0 <br>
  4   1   1   1 <br>
  4   1   2   0 <br>
  4   1   2   1 <br>
  4   2   0   0 <br>
  4   2   0   0 <br>
  4   2   1   0 <br>
  4   2   1   1 <br>
  4   2   2   1 <br>
  4   2   2   1
</details>
<br>

LMC gives exactly 90 rows where every single row has a duplicate. So as I understand, it gives OA with 45 runs. But if one tries to create series like `arraydata_t adata(s, 45, 3, 4);` then you get `Found 0 arrays in total, only 0 in LMC form, total is 0`. Why? Is not that true that if you drop duplicates, then you get a correct orthogonal array with less runs?

Also, I do not understand the purpose of [this array](http://pietereendebak.nl/oapackage/series/gmaarray-t3-90.5-3-3-2-gma.oa) as it has 90 runs and it is basically all possible combinations for the given factors and hence the oa must have maximal strength of 4 instead of 3 as stated. 

I am a bit curious about the issue, though I have little knowledge about the Orthogonal Arrays. That would be great if you could give me a small hint or correct my thoughts above.

**Comment by peendebak** [comment]
@AntonGitName The results you show are as they should be. The output of the code above generates 39 arrays, which is correct since there are 39 isomorphism classes in OA(90; 3; 5<sup>1</sup>3<sup>2</sup>2<sup>1</sup>). Each array has 90 rows (runs) and 4 factors. 

For the array you quote not every row has a duplicate. For example row 7 has no duplicate.

There are no arrays in  OA(45; 3; 5<sup>1</sup>3<sup>2</sup>2<sup>1</sup>) because the 2 is not a divisor of 45. 

The software package generated series of arrays of a given strength or higher. So if you generate the series OA(90; 3; 5<sup>1</sup>3<sup>2</sup>2<sup>1</sup>) you end up with all strength 3 and strenght 4 designs. From the 39 arrays in this class there is a single GMA desigin which turns out to be of strength 4.

I hope this explanation helps, if not ask again.

**Comment by AntonGitName** [comment]
@peendebak Yep, thank you very much!
